// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelRoute.Infra.Contexts;

#nullable disable

namespace TravelRoute.Infra.Migrations
{
    [DbContext(typeof(TravelRouteDbContext))]
    partial class TravelRouteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TravelRoute.Domain.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c70267a-b495-4fa5-bb46-e69676e564d6"),
                            Cost = 10,
                            Destination = "BRC",
                            Origin = "GRU"
                        },
                        new
                        {
                            Id = new Guid("2e229838-22f8-49e9-a5c8-39583f6dffe4"),
                            Cost = 5,
                            Destination = "SCL",
                            Origin = "BRC"
                        },
                        new
                        {
                            Id = new Guid("7a1f9b9f-d96d-4dea-807d-59da2015cffc"),
                            Cost = 75,
                            Destination = "CDG",
                            Origin = "GRU"
                        },
                        new
                        {
                            Id = new Guid("94a561ad-860a-4dc3-855b-05ccc0bb3b1e"),
                            Cost = 20,
                            Destination = "SCL",
                            Origin = "GRU"
                        },
                        new
                        {
                            Id = new Guid("459fab17-8405-40cc-aeb8-1f5aacf08380"),
                            Cost = 56,
                            Destination = "ORL",
                            Origin = "GRU"
                        },
                        new
                        {
                            Id = new Guid("47e22155-f14a-4317-b9d5-0e0a6878fe1b"),
                            Cost = 5,
                            Destination = "CDG",
                            Origin = "ORL"
                        },
                        new
                        {
                            Id = new Guid("5b13d512-3818-4617-98a6-44689c9b8bd2"),
                            Cost = 20,
                            Destination = "ORL",
                            Origin = "SCL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
